### ISSUE TITLE
version branch 1.2.3 TLSExtSignatureAndHashAlgorithm gives Attribute error

### ISSUE THREAD

**Issue by bestrocker221** [tintinweb/scapy-ssl_tls#109]
I use version 1.2.3 of scapy and when i tried to use that extension it gives me 

Attribute error: algorithms

The fix is changing the 

`XFieldLenField("length", None, length_of="algorithms", fmt="H"),`

to 

`XFieldLenField("length", None, length_of="algs", fmt="H"),`

in ssl_tls.py : row420

**Comment by tintinweb** [comment]
Hi @bestrocker221,

thanks for the report.  This issue has been fixed in master already https://github.com/tintinweb/scapy-ssl_tls/commit/c3c947aebdda563342ce6650f84f6fe92de2358f but did not make it into an official release yet. In order to maintain compatibility (as current master is not fully compatible with 1.2.x branch) I'll pull in that commit and draft a maintenance release that should be ready within the next days. I will keep you updated.

tin

**Comment by bestrocker221** [comment]
Thank you for your work!

**Comment by tintinweb** [comment]
released as https://github.com/tintinweb/scapy-ssl_tls/releases/tag/v1.2.3.3 and now available via pip
