### ISSUE TITLE
make ssl_tls_crypto available in ssl_tls

### ISSUE THREAD

**Issue by tintinweb** [tintinweb/scapy-ssl_tls#29]
ssl_tls.py is the entrypoint for all ssl_tls related layers and functionality and should therefore allow to access the TLSSessionCTX/.... without having to explicitly import it from ssl_tls_crypto. We should also make sure that one can still use the layers without having to install pyCrypto (try_catch:ImportError).

**Comment by alexmgr** [comment]
This is going to be close to impossible due to how this was designed. ssl_tls is going to try to import ssl_tls_crypto whilst being itself incompletely compiled. Which will cause ssl_tls_crypto to fail to import ssl_tls, which will in turn fail ;)
A simple fix is to add ssl_tls_crypto to the layers declaration in scapy. I'd prefer that approach.

Regarding the pycrypto dependancy, It's already made mandatory by setuptools. TBH, I wouldn't bother handling the non pycrypto case. Who's the cheap guy who can't spare 100k of disk space and bandwidth ;)?

**Comment by tintinweb** [comment]
It is more less not the 100k but the hassle making pyCrypto compile on windows with all its dependencies :). Anyway, I agree that we should not care about this as we added it to the requirements and there are pre-compiled (you never know what you get) pyCrypto binaries for the lazy ones :)

**Comment by alexmgr** [comment]
Not worth the effort I think

**Comment by tintinweb** [comment]
agreed
