### ISSUE TITLE
Configuration option to dissect SSL/TLS on non-standard ports

### ISSUE THREAD

**Issue by gattjoe** [tintinweb/scapy-ssl_tls#52]
By default scapy-ssl_tls will not identify or dissect SSL/TLS packets on non-standard ports (i.e., != TCP 443 or TCP 4443). I found that if you manually add entries to the "bind magic" [section](https://github.com/tintinweb/scapy-ssl_tls/blob/master/scapy_ssl_tls/ssl_tls.py#L1031) of ssl_tls.py, you can get it to work. For example, TCP 5222 for encrypted GTalk. This is less of an issue and more of an enhancement request, perhaps the "bind magic" section should be added to ssl_tls_registry.py so that users can manually modify it? 

I've only started using this tool yesterday, so I am nowhere near qualified enough to submit my own pull request for this.

**Comment by tintinweb** [comment]
`ssl_tls_registry` is an autogenerated file of with a Name/Constants mapping as specified by IANA and as such should not contain any active code. You should not even have to modify that file. In the `#bind magic` section of `ssl_tls` we bind the registered default ports for TCP/UDP (and for convenience the experimental 4433) to scapy's layer hierarchy in order for it to auto-resolve TCP443 packets as TLS/SSL.
From a library perspective it would not make much sense to register the tls layers for non-default ports as it will propably have a negative performance impact on scapy.

Since I cannot come up with a reason to modify the library code for your use-case I'd recommend to explicitly do the binding for this specific purpose in your script then. Here's an example:

    import scapy
    from scapy.all import *
    from scapy_ssl_tls.ssl_tls import *  # in case you're missing the scapy config patch that autoloads the ssl layers

    bind_layers(TCP, TLS, dport=5222)
    # your code

let me know if that does the trick for you.
